# Generated by Django 2.1.1 on 2018-09-13 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20180912_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='summmary',
            new_name='summary',
        ),
    ]
